# Nanuk — btop (SUPER+SHIFT+T). btop reescribe este archivo al salir, por eso
# se COPIA a ~/.config/btop/btop.conf solo la primera vez (no es un enlace).
color_theme = "nanuk"
theme_background = True
truecolor = True
rounded_corners = False
graph_symbol = "braille"
vim_keys = True
update_ms = 1500
proc_sorting = "cpu lazy"
proc_tree = False
